version: '3.1'

services:

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: abc1234
      MYSQL_DATABASE: spring-sample
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring123
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  sonarqube:
    image: sonarqube:latest
    restart: always
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - ./volumes/sonarqube/conf:/opt/sonarqube/conf
      - ./volumes/sonarqube/data:/opt/sonarqube/data
      - ./volumes/sonarqube/extensions:/opt/sonarqube/extensions
    environment:
      - sonar.jdbc.username=sonarqube
      - sonar.jdbc.password=s0N@r851
      - sonar.jdbc.url=jdbc:postgresql://postgres/sonarqube

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
        - ./volumes/sonarqube/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=s0N@r851

networks:
  default:
    external:
      name: proxy